### ISSUE TITLE
Memory leak in draw func

### ISSUE THREAD

**Issue by marcelgruber** [ashiishme/react-sine-wave#3]
Hello. Looks like we have a memory leak in the `draw` function in `wave.ts`. I can see the draw function being called in a continuous loop even when the component has been unmounted. I was getting a console error regarding this.

![Screen Shot 2021-07-18 at 7 02 45 PM](https://user-images.githubusercontent.com/4956028/126088517-f9f505a5-b6e9-4d5b-ac7b-ea3b551525e8.png)

**Comment by ashiishme** [comment]
@marcelgruber  Thank you for flagging this issue. Can you please share the error as well? It will help me to debug easily.

Also, please include an information about how to regenerate the issue.

**Comment by marcelgruber** [comment]
@ashiishme 

Here is the error:

![Screen Shot 2021-07-21 at 4 31 50 PM](https://user-images.githubusercontent.com/4956028/126568331-6fc19d60-28a3-449f-b64d-d716e88a35ff.png)

The error shows up when I resize the window.

**Comment by ashiishme** [comment]
@marcelgruber  I tried to regenerate the issue but it is still working in my case.

Are you trying to implemented the wave on your project? There are no state used on this wave project.

**Comment by marcelgruber** [comment]
@ashiishme yes, implementing in my project.

State is used here: https://github.com/ashiishme/react-sine-wave/blob/main/src/app/components/canvas/canvas.tsx

**Comment by ashiishme** [comment]
@marcelgruber  The error has to do something with your implementation. You can add a conditional flag and toggle it using clean up function inside `useEffect`. Something like this:

```js
useEffect(() => {
  let myFlag = true;
  if (myFlag) setState({...}); // you state thing here
  return () => { isMounted = false }; // toggle flag on clean up function so that when unmounted occurs the state doesn't try to change / update that results in the memory leak error.
}, []); 
```

**Comment by ashiishme** [comment]
@marcelgruber The error has to do something with your implementation. You can add a conditional flag and toggle it using clean up function inside useEffect. Something like this:

```js
useEffect(() => {
  let myFlag = true;
  if (myFlag) setState({...}); // you state thing here
  return () => { myFlag = false }; // toggle flag on clean up function so that when unmounted occurs the state doesn't try to change / update that results in the memory leak error.
}, []);
```
